--HAVING CLAUSE

--RETURNS THE COLUMNS OF GENDER ADN AVEARGE OF AGE FROM THE employee_demographics TABLE GROUPING BY GEDER AND HAVING A CONDITION OF AVERAGE AGE GREATER THAN 40
SELECT gender, AVG(age)
FROM employee_demographics
GROUP BY gender
HAVING AVG(age)>40;