--WHERE 

 --RETURNS THE ROW HAVING SAME FIRSTNAME AS LESLIE
SELECT* 
FROM employee_demographics
WHERE first_name='Leslie';  
 
 --RETURNS THE ROW IN WHICH THE SALARY SPECIFIED IS EQUAL OR GREATER THAN 50000
SELECT*
FROM employee_salary
WHERE salary>=50000; 


--RETURNS ALL THE ROW WHERE THE GENDER IS NOT FEMALE FROM THE EMPLOYEE_DEMOGRAPHICS TABLE
select*
FROM employee_demographics
WHERE gender!='Female';

--RETURNS ALL THE ROWS WHERE THE BIRTHDATE IS AFTER 1985 AND THE GENDER IS MALE FROM THE EMPLOYEE_DEMOGRAPHICS
SELECT*
FROM employee_demographics
WHERE birth_date>'1985-01-01'
AND gender='Male';

--RETURNS ALL THE ROWS WHERE THE FIRSTNAME IS LESLIE AND AGE IS 44 OR WHERE THE AGE I SMORE THAN 55 FROM THE EMPLOYEE_DEMOGRAPHUCS
SELECT*
FROM employee_demographics
WHERE (first_name='Leslie' AND age=44) OR age>55;

--LIKE 

--RETURNS FIRSNAME STARTS WITH JER FROM THE EMPLOYEE_DEMOGRAPHICS
SELECT*
FROM employee_demographics
WHERE first_name LIKE 'Jer%';

--RETURNS ALL THE ROWS WHERE THE FIRSTNAME STARTS WITH A FROM THE EMPLOYEE_DEMOGRAPHICS TABLE
SELECT*
FROM employee_demographics
WHERE first_name LIKE 'A%';

--RETURNS ALL THE ROWS WHERE THE FIRSTNAME STARTS WITH A FROM THE EMPLOYEE_DEMOGRAPHICS TABLE
SELECT*
FROM employee_demographics
WHERE first_name LIKE 'a__%';

--RETURNS ALL THE ROWS WHERE THE BIRTHYEAR IS 1994 FROM THE EMPLOYEE_DEMPGRAPHICS
SELECT*
FROM employee_demographics
WHERE birth_date LIKE '1994%';